version: '3'
services:
  wingetty:
    container_name: wingetty
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/thilojaeggi/wingetty:stable
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - instance_volume:/app/instance # This is where the database will be stored
      - packages_volume:/app/app/packages # This is where the packages will be stored
    environment:
      - WINGETTY_SQLALCHEMY_DATABASE_URI="sqlite:///database.db" # You can use any database URI supported by SQLAlchemy, so you can use MySQL, PostgreSQL, etc.
      - WINGETTY_SECRET_KEY="secret" # Change this to a random string
      - WINGETTY_ENABLE_REGISTRATION=0 # Enable open registration (0 = disabled, 1 = enabled)
      - WINGETTY_REPO_NAME="WinGetty" # You can change this to whatever you want
      - LOG_LEVEL=INFO # Change this to DEBUG if you want to see more logs
      - TZ=Europe/Paris # Change this to your timezone
volumes:
  instance_volume:
  packages_volume:
